sudo: required
language: c

dist: trusty

compiler:
  - gcc
  - clang

env: CFLAGS="-g -fsanitize=address"

install:
  # the following is a work-around to solve the
  # "too old autoconf-archive" problem
  - mkdir tmp
  - cd tmp
  - git clone git://git.sv.gnu.org/autoconf-archive.git
  - sudo cp autoconf-archive/m4/* /usr/share/aclocal
  - cd ..
  - rm -rf tmp

script:
  - sudo find / -name ax_is_release.*
  - autoreconf --force --verbose --install
  - ./configure --enable-Werror
  - make
  - make check
  - cat tests/test-suite.log
